# Generated by Django 5.2.15 on 2026-09-17 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('subject', models.CharField(max_length=160, verbose_name='sujet')),
                ('message', models.TextField(verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='reçu le')),
                ('is_read', models.BooleanField(default=False, verbose_name='lu')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, verbose_name='code')),
                ('title', models.CharField(max_length=80, verbose_name='titre')),
                ('description', models.TextField(verbose_name='description')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'axe',
                'verbose_name_plural': 'axes',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('education', 'Formation'), ('experience', 'Expérience'), ('achievement', 'Repère')], max_length=20, verbose_name='type')),
                ('title', models.CharField(max_length=140, verbose_name='titre')),
                ('organization', models.CharField(blank=True, max_length=140, verbose_name='organisation')),
                ('period', models.CharField(max_length=80, verbose_name='période')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'étape',
                'verbose_name_plural': 'parcours',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=80, verbose_name='nom affiché')),
                ('first_name', models.CharField(max_length=60, verbose_name='prénom')),
                ('last_name', models.CharField(blank=True, max_length=60, verbose_name='nom')),
                ('headline', models.CharField(max_length=180, verbose_name='accroche')),
                ('tagline', models.CharField(blank=True, max_length=240, verbose_name='sous-titre')),
                ('bio', models.TextField(verbose_name='biographie')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='localisation')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='téléphone')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('availability', models.CharField(blank=True, max_length=160, verbose_name='disponibilité')),
                ('photo', models.ImageField(blank=True, upload_to='profile/', verbose_name='photo')),
                ('cv', models.FileField(blank=True, upload_to='cv/', verbose_name='CV')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'profil',
                'verbose_name_plural': 'profil',
            },
        ),
        migrations.CreateModel(
            name='SiteStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80, verbose_name='libellé')),
                ('value', models.CharField(max_length=20, verbose_name='valeur')),
                ('suffix', models.CharField(blank=True, max_length=12, verbose_name='suffixe')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'statistique',
                'verbose_name_plural': 'statistiques',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nom')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'catégorie de compétence',
                'verbose_name_plural': 'catégories de compétences',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nom')),
                ('level', models.PositiveSmallIntegerField(default=70, help_text='0 à 100', verbose_name='niveau')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.skillcategory', verbose_name='catégorie')),
            ],
            options={
                'verbose_name': 'compétence',
                'verbose_name_plural': 'compétences',
                'ordering': ['category__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='titre')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('excerpt', models.CharField(max_length=240, verbose_name='extrait')),
                ('description', models.TextField(verbose_name='description')),
                ('category', models.CharField(choices=[('data', 'Ingénierie data'), ('deep', 'Deep learning'), ('web', 'Plateforme Django'), ('math', 'Math & info'), ('vibe', 'Vibe coding')], max_length=12, verbose_name='catégorie')),
                ('role', models.CharField(blank=True, max_length=120, verbose_name='rôle')),
                ('year', models.PositiveSmallIntegerField(verbose_name='année')),
                ('live_url', models.URLField(blank=True, verbose_name='lien live')),
                ('repo_url', models.URLField(blank=True, verbose_name='dépôt')),
                ('cover', models.ImageField(blank=True, upload_to='projects/', verbose_name='couverture')),
                ('accent', models.CharField(default='#d4ff4a', max_length=7, verbose_name="couleur d'accent")),
                ('featured', models.BooleanField(default=False, verbose_name='mis en avant')),
                ('published', models.BooleanField(default=True, verbose_name='publié')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='projects', to='core.tag')),
            ],
            options={
                'verbose_name': 'projet',
                'verbose_name_plural': 'projets',
                'ordering': ['order', '-year', '-created_at'],
            },
        ),
    ]
