# Generated by Django 5.2.15 on 2026-09-17 00:30

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='titre')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('issuer', models.CharField(max_length=140, verbose_name='organisme')),
                ('kind', models.CharField(choices=[('cert', 'Certificat'), ('diploma', 'Diplôme'), ('course', 'Formation'), ('badge', 'Badge')], default='cert', max_length=12, verbose_name='type')),
                ('issued_on', models.DateField(verbose_name='obtenu le')),
                ('credential_id', models.CharField(blank=True, max_length=80, verbose_name='identifiant')),
                ('credential_url', models.URLField(blank=True, verbose_name='lien de vérification')),
                ('file', models.FileField(blank=True, upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='fichier PDF')),
                ('image', models.ImageField(blank=True, upload_to='certificates/images/', verbose_name='visuel')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('published', models.BooleanField(default=True, verbose_name='publié')),
                ('featured', models.BooleanField(default=False, verbose_name='mis en avant')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'certificat',
                'verbose_name_plural': 'certificats',
                'ordering': ['order', '-issued_on'],
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='titre')),
                ('language', models.CharField(default='FR', max_length=8, verbose_name='langue')),
                ('version', models.CharField(blank=True, max_length=40, verbose_name='version')),
                ('summary', models.TextField(blank=True, verbose_name='résumé')),
                ('file', models.FileField(blank=True, upload_to='cv/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='fichier PDF')),
                ('published', models.BooleanField(default=True, verbose_name='publié')),
                ('is_primary', models.BooleanField(default=False, verbose_name='CV principal')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CV',
                'ordering': ['-is_primary', 'order', '-updated_at'],
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cv',
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, verbose_name='site web'),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='dernière mise à jour'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.PositiveSmallIntegerField(default=70, help_text='0 à 100 — augmente-le dans l’admin au fil du temps', verbose_name='niveau actuel'),
        ),
        migrations.CreateModel(
            name='SkillProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(verbose_name='niveau')),
                ('recorded_at', models.DateField(default=datetime.date.today, verbose_name='date')),
                ('note', models.CharField(blank=True, max_length=160, verbose_name='note')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.skill', verbose_name='compétence')),
            ],
            options={
                'verbose_name': 'évolution de compétence',
                'verbose_name_plural': 'historique des compétences',
                'ordering': ['-recorded_at', '-id'],
            },
        ),
    ]
