# Generated by Django 5.2.15 on 2026-09-17 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_certificate_curriculum_remove_profile_cv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='adresse IP')),
                ('failures', models.PositiveSmallIntegerField(default=0, verbose_name='échecs')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='bloqué jusqu’à')),
                ('last_attempt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'verrou d’accès',
                'verbose_name_plural': 'verrous d’accès',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='cover_from_live',
            field=models.BooleanField(default=False, verbose_name='aperçu capturé depuis le lien'),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, help_text='Si tu colles l’URL, le portfolio capture la page d’accueil comme image.', verbose_name='lien live'),
        ),
    ]
