# Generated by Django 5.2.15 on 2026-09-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_accesslock_project_cover_from_live_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='also_known_as',
            field=models.CharField(blank=True, default='Arsène', help_text='Nom indexé pour Google, ex. Arsène.', max_length=80, verbose_name='aussi connu comme'),
        ),
    ]
