# Generated by Django 5.2.15 on 2026-09-17 01:25

from django.db import migrations, models


def fill_tag_categories(apps, schema_editor):
    from core.models import TAG_CATEGORY_MAP

    Tag = apps.get_model("core", "Tag")
    for name, cats in TAG_CATEGORY_MAP.items():
        Tag.objects.filter(name=name).update(categories=cats)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_also_known_as'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='course_url',
            field=models.URLField(blank=True, help_text='Si la formation était en ligne, colle ici le lien du cours.', verbose_name='lien de la formation'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, help_text='Numéro avec indicatif, ex. 243812345678.', max_length=40, verbose_name='WhatsApp'),
        ),
        migrations.AddField(
            model_name='tag',
            name='categories',
            field=models.JSONField(blank=True, default=list, help_text='Le tag n’est proposé que pour ces catégories de projet.', verbose_name='catégories projet'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='credential_url',
            field=models.URLField(blank=True, help_text='URL du certificat (vérification, badge, PDF en ligne…).', verbose_name='lien du certificat'),
        ),
        migrations.RunPython(fill_tag_categories, migrations.RunPython.noop),
    ]
